name: CI

on:
  push:
    branches: [ master, QA, DEV ]
  pull_request:
    branches: [ master, QA, DEV ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release
      - name: Test
        run: |
          if [ -d "tests" ]; then
            dotnet test --no-build --configuration Release --verbosity normal
          else
            echo "No tests found"
          fi
